name: No release

on:
  workflow_dispatch:

jobs:
  call-release:
    name: Release
    uses: ./.github/workflows/release-template.yml
    with:
      stack-name: 'TestStack'
      build-release: false
    secrets: inherit
