name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      NEW_RELEASE_PUBLISHED: ${{ steps.semantic.outputs.new_release_published }}
      NEW_RELEASE_VERSION: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Create new release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          extra_plugins: |
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
